[tool.poetry]
name = "summa"
version = "0.1.0"
description = ""
authors = ["Pasha Podolsky <ppodolsky@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiogrpcclient = "^1.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
