// @generated by protobuf-ts 2.9.1 with parameter use_proto_field_name
// @generated from protobuf file "public_service.proto" (package "summa.proto", syntax proto3)
// tslint:disable
import { SearchResponse } from "./query";
import { SearchRequest } from "./search_service";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service summa.proto.PublicApi
 */
export const PublicApi = new ServiceType("summa.proto.PublicApi", [
    { name: "search", options: {}, I: SearchRequest, O: SearchResponse }
]);
