// @generated by protobuf-ts 2.9.1 with parameter use_proto_field_name
// @generated from protobuf file "search_service.proto" (package "summa.proto", syntax proto3)
// tslint:disable
import { SearchResponse } from "./query";
import { SearchRequest } from "./query";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service summa.proto.SearchApi
 */
export const SearchApi = new ServiceType("summa.proto.SearchApi", [
    { name: "search", options: {}, I: SearchRequest, O: SearchResponse }
]);
