remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
title: Summa
description: Fast full-text search server
show_downloads: false
aux_links:
  "Summa on GitHub":
    - "//github.com/izihawa/summa"