# yamllint disable

name: Docker images
on:
  release:
    types: [ published ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker buildx build \
            --push \
            --tag izihawa/summa-server:testing \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
