# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import beacon_service_pb2 as beacon__service__pb2


class BeaconApiStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.publish_index = channel.unary_unary(
                '/summa.proto.BeaconApi/publish_index',
                request_serializer=beacon__service__pb2.PublishIndexRequest.SerializeToString,
                response_deserializer=beacon__service__pb2.PublishIndexResponse.FromString,
                )


class BeaconApiServicer(object):
    """Service
    """

    def publish_index(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeaconApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'publish_index': grpc.unary_unary_rpc_method_handler(
                    servicer.publish_index,
                    request_deserializer=beacon__service__pb2.PublishIndexRequest.FromString,
                    response_serializer=beacon__service__pb2.PublishIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'summa.proto.BeaconApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BeaconApi(object):
    """Service
    """

    @staticmethod
    def publish_index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/summa.proto.BeaconApi/publish_index',
            beacon__service__pb2.PublishIndexRequest.SerializeToString,
            beacon__service__pb2.PublishIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
